min_clusters: 12
max_clusters: 14
min_nCount_RNA: 20
max_nFeature_negprobes: 0.5

#UMAP features to plot
umap_features: INS,KRT8,KRT17,LYZ,S100A6

src_path: "CosMx_Spatial"
output_path: "analysis"

insitutype_profile_ref: /cristealab/ajordan/projects/BTC_analysis/data/external/insitutype_references/Pancreas.profiles.csv

polarity_genesets: /cristealab/ajordan/projects/BTC_analysis/data/external/gene_sets/basal_classical_and_fibroblast_gene_sets.csv

samples:
  PCA429:
    - /cristealab/ajordan/projects/BTC_analysis/data/processed/cosmx/human/resegmented_data/PCA429
